<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Получение-информации-о-данных" data-toc-modified-id="Получение-информации-о-данных-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Получение информации о данных</a></span></li><li><span><a href="#Обработка-пропусков" data-toc-modified-id="Обработка-пропусков-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Обработка пропусков</a></span></li><li><span><a href="#Обработка-редких-категорий" data-toc-modified-id="Обработка-редких-категорий-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Обработка редких категорий</a></span></li><li><span><a href="#Обработка-выбросов" data-toc-modified-id="Обработка-выбросов-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Обработка выбросов</a></span></li><li><span><a href="#Построение-новых-признаков" data-toc-modified-id="Построение-новых-признаков-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Построение новых признаков</a></span><ul class="toc-item"><li><span><a href="#Кодирование-категориальных-признаков" data-toc-modified-id="Кодирование-категориальных-признаков-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Кодирование категориальных признаков</a></span></li><li><span><a href="#Построение-новых-признаков-на-основе-количественных" data-toc-modified-id="Построение-новых-признаков-на-основе-количественных-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Построение новых признаков на основе количественных</a></span></li></ul></li><li><span><a href="#Ковариация-и-корреляция-данных" data-toc-modified-id="Ковариация-и-корреляция-данных-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Ковариация и корреляция данных</a></span></li><li><span><a href="#Сохранение-результатов" data-toc-modified-id="Сохранение-результатов-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Сохранение результатов</a></span></li></ul></div>

# Вебинар 2. Предобработка данных.

**Data Science проект:**

1. Постановка задачи
2. Получение данных
_________
3. **Анализ данных**
4. Визуализация данных
5. **Предобработка данных**
6. **Генерация новых признаков**
7. Построение модели
8. Оценка качества
______
9. Внедрение модели
10. Мониторинг качества и улучшение модели

**Подключение библиотек и скриптов**

In [1]:
import numpy as np
import pandas as pd

**Пути к директориям и файлам**

In [2]:
DATASET_PATH = '../data/housing.csv'
PREPARED_DATASET_PATH = '../data/housing_prepared.csv'

### Загрузка данных

**Описание датасета**

Статистические данные о группах домов в Калифорнии, основанные на переписи 1990 года.   

A block group is the smallest geographical unit for which the U.S. Census Bureau publishes sample data (a block group typically has a population of 600 to 3,000 people).

* **longitude** - долгота группы
* **latitude** - широта группы
* **housing_median_age** - медианный возраст дома в группе (Median age of a house within a block)
* **total_rooms** - общее количество комнат в группе домов (Total number of rooms within a block)
* **total_bedrooms** - общее количество спален в группе домов (Total number of bedrooms within a block)
* **population** - количество проживающих в группе домов (Total number of people residing within a block)
* **households** - количество семей/общин (Total number of households, a group of people residing within a home unit, for a block)
* **ocean_proximity** - близость океана
* **median_income** - медианный доход общины (Median income for households within a block of houses, measured in tens of thousands of US Dollars)
* **median_house_value** - медианная стоимость дома (Median house value for households within a block, measured in US Dollars)

In [3]:
df = pd.read_csv(DATASET_PATH, index_col='id')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
id,,,,,,,,,,
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
df.shape

(20640, 10)

### Получение информации о данных

In [5]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  19918 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20041 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.7+ MB

In [7]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [8]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,19918.000000,20640.000000,20433.000000,20041.000000,20640.000000,20640.000000,20640.000000
mean,-119.471242,35.036934,28.653630,2635.763081,537.870553,1425.418243,499.539680,3.870671,206855.816909
std,5.041408,94.903955,12.576796,2181.615252,421.385070,1135.185798,382.329753,1.899822,115395.615874
min,-124.350000,-13534.030000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,786.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1165.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1726.000000,605.000000,4.743250,264725.000000
max,122.030000,1327.130000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [9]:
df.describe(include='object')

       ocean_proximity
count            20640
unique               6
top          <1H OCEAN
freq              9127

In [10]:
df['ocean_proximity'].value_counts()

<1H OCEAN     9127
INLAND        6542
NEAR OCEAN    2655
NEAR BAY      2288
-               23
ISLAND           5
Name: ocean_proximity, dtype: int64

In [11]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', '-', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [12]:
df['ocean_proximity'].nunique()

6

### Обработка пропусков

In [13]:
len(df) - df.count()

longitude               0
latitude                0
housing_median_age    722
total_rooms             0
total_bedrooms        207
population            599
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [14]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age    722
total_rooms             0
total_bedrooms        207
population            599
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [15]:
round(df.isna().mean() * 100, 2)

longitude             0.0
latitude              0.0
housing_median_age    3.5
total_rooms           0.0
total_bedrooms        1.0
population            2.9
households            0.0
median_income         0.0
median_house_value    0.0
ocean_proximity       0.0
dtype: float64

**housing_median_age**

In [ ]:
# 0 вариант замены - на константу
# df['housing_median_age'] = df['housing_median_age'].fillna(0)

In [16]:
df['housing_median_age'].mean(), df['housing_median_age'].median()

(28.653629882518324, 29.0)

In [17]:
# 1 вариант замены - на среднее арифметическое или медиану признака
# df['housing_median_age'] = df['housing_median_age'].fillna(df['housing_median_age'].mean())

In [18]:
# 2 вариант замены - на медиану признака в группе
df.groupby(['ocean_proximity'])['housing_median_age'].median()

ocean_proximity
-             26.0
<1H OCEAN     30.0
INLAND        23.0
ISLAND        52.0
NEAR BAY      39.0
NEAR OCEAN    29.0
Name: housing_median_age, dtype: float64

In [19]:
df.loc[df['housing_median_age'].isna(), 'housing_median_age'] =\
    df.groupby(['ocean_proximity'])['housing_median_age'].transform(lambda x: x.median())

In [20]:
df['housing_median_age'].describe()

count    20640.000000
mean        28.640455
std         12.384944
min          1.000000
25%         19.000000
50%         29.000000
75%         37.000000
max         52.000000
Name: housing_median_age, dtype: float64

**total_bedrooms**

In [21]:
df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)

**population**

In [22]:
df['population'].fillna(df['population'].median(), inplace=True)

**ocean_proximity**

In [23]:
df['ocean_proximity'].mode()[0]

'<1H OCEAN'

In [24]:
df.replace({'ocean_proximity' : {'-' : df['ocean_proximity'].mode()[0]}}, inplace=True)

In [25]:
df['ocean_proximity'].value_counts()

<1H OCEAN     9150
INLAND        6542
NEAR OCEAN    2655
NEAR BAY      2288
ISLAND           5
Name: ocean_proximity, dtype: int64

### Обработка редких категорий

In [26]:
df.replace({'ocean_proximity' : {'ISLAND' : 'NEAR OCEAN'}}, inplace=True)
df['ocean_proximity'].value_counts()

<1H OCEAN     9150
INLAND        6542
NEAR OCEAN    2660
NEAR BAY      2288
Name: ocean_proximity, dtype: int64

### Обработка выбросов

In [27]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.471242,35.036934,28.640455,2635.763081,536.838857,1417.860562,499.539680,3.870671,206855.816909
std,5.041408,94.903955,12.384944,2181.615252,419.391878,1119.445348,382.329753,1.899822,115395.615874
min,-124.350000,-13534.030000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,19.000000,1447.750000,297.000000,797.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1165.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,643.250000,1701.000000,605.000000,4.743250,264725.000000
max,122.030000,1327.130000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

**longitude**  
[ссылка на карту](https://www.mapsdirections.info/ru/GPS-%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D1%8B-Google-%D0%9A%D0%B0%D1%80%D1%82%D0%B0%D1%85.html)

In [28]:
df['longitude'].describe()

count    20640.000000
mean      -119.471242
std          5.041408
min       -124.350000
25%       -121.800000
50%       -118.490000
75%       -118.010000
max        122.030000
Name: longitude, dtype: float64

In [29]:
df[(df['longitude'] < -125) | (df['longitude'] > -114)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
id,,,,,,,,,,
3479,118.51,34.29,29.0,1287.0,194.0,525.0,187.0,6.4171,319300.0,<1H OCEAN
5904,118.43,34.29,39.0,1769.0,410.0,1499.0,390.0,3.1212,153500.0,<1H OCEAN
8405,118.36,33.93,40.0,1625.0,500.0,2036.0,476.0,2.6298,156500.0,<1H OCEAN
8636,118.41,33.88,43.0,2492.0,449.0,1033.0,437.0,7.9614,500001.0,<1H OCEAN
13051,121.29,38.61,17.0,13553.0,2474.0,6544.0,2359.0,3.9727,132700.0,INLAND
15263,117.27,33.02,21.0,2144.0,340.0,928.0,344.0,5.7980,286100.0,NEAR OCEAN
17085,0.00,37.47,33.0,1266.0,415.0,1991.0,334.0,2.9200,202800.0,NEAR OCEAN
17359,0.00,34.88,4.0,3680.0,559.0,1678.0,569.0,5.0639,201700.0,<1H OCEAN
18551,122.03,36.96,28.0,1607.0,421.0,926.0,385.0,2.4250,216100.0,NEAR OCEAN
19423,0.00,37.69,5.0,9601.0,1639.0,4449.0,1575.0,4.5332,195500.0,INLAND

In [30]:
df.loc[df['longitude'] > 0, 'longitude'] = df.loc[df['longitude'] > 0, 'longitude'] * -1

In [31]:
df.drop(df[df['longitude'] == 0].index, inplace=True)
df.shape

(20637, 10)

**latitude**

In [32]:
df[(df['latitude'] < 32) | (df['latitude'] > 42)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
id,,,,,,,,,,
8283,-118.13,-13534.03,45.0,1016.0,172.0,361.0,163.0,7.5000,434500.0,NEAR OCEAN
12772,-121.42,1327.13,23.0,2217.0,536.0,1203.0,507.0,1.9412,73100.0,INLAND

In [33]:
#df.loc[(df['latitude'] < 32) | (df['latitude'] > 42), 'latitude'] = df['latitude'].median()
df.drop(df[(df['latitude'] < 32) | (df['latitude'] > 42)].index, inplace=True)
df.shape

(20635, 10)

In [34]:
df.groupby('ocean_proximity')['latitude'].median()

ocean_proximity
<1H OCEAN     34.03
INLAND        36.97
NEAR BAY      37.79
NEAR OCEAN    33.79
Name: latitude, dtype: float64

**'households', 'population', 'total_rooms', 'total_bedrooms'**

In [35]:
df[['households', 'population', 'total_rooms', 'total_bedrooms']].describe()

         households    population   total_rooms  total_bedrooms
count  20635.000000  20635.000000  20635.000000    20635.000000
mean     499.508166   1417.734916   2635.540102      536.807996
std      382.293543   1119.348333   2181.276630      419.363925
min        1.000000      3.000000      2.000000        1.000000
25%      280.000000    797.000000   1448.000000      297.000000
50%      409.000000   1165.000000   2127.000000      435.000000
75%      605.000000   1701.000000   3147.500000      643.500000
max     6082.000000  35682.000000  39320.000000     6445.000000

### Построение новых признаков

#### Кодирование категориальных признаков
**Label Encoding**

In [36]:
df['ocean_proximity'].value_counts()

<1H OCEAN     9149
INLAND        6540
NEAR OCEAN    2658
NEAR BAY      2288
Name: ocean_proximity, dtype: int64

**Label Encoding**

In [37]:
dict = {'<1H OCEAN' : 1,
        'INLAND'    : 2,
        'NEAR OCEAN': 3,
        'NEAR BAY'  : 4}

df['ocean_proximity'].replace(dict, inplace=False).value_counts()

1    9149
2    6540
3    2658
4    2288
Name: ocean_proximity, dtype: int64

**One-Hot Encoding**

Преобразуем категориальный признак "ocean_proximity" в несколько бинарных

![](oh.png)

In [38]:
ocean_pr = pd.get_dummies(df['ocean_proximity'])
ocean_pr

       <1H OCEAN  INLAND  NEAR BAY  NEAR OCEAN
id
0              0       0         1           0
1              0       0         1           0
2              0       0         1           0
3              0       0         1           0
4              0       0         1           0
...          ...     ...       ...         ...
20635          0       1         0           0
20636          0       1         0           0
20637          0       1         0           0
20638          0       1         0           0
20639          0       1         0           0

[20635 rows x 4 columns]

In [39]:
#df = pd.concat([df, ocean_pr], axis=1)
df[ocean_pr.columns] = ocean_pr
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,<1H OCEAN,INLAND,NEAR BAY,NEAR OCEAN
id,,,,,,,,,,,,,,
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,0,1,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,0,0,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,0,0,1,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,0,0,1,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,0,0,1,0

#### Построение новых признаков на основе количественных

In [40]:
df['rooms_per_household'] = df['total_rooms'] / df['households']
df['bedrooms_per_household'] = df['total_bedrooms'] / df['households']
df['persons_per_household'] = df['population'] / df['households']
df['income_per_person'] = df['median_income'] * 10000 / df['population']

In [41]:
df[['rooms_per_household', 'bedrooms_per_household', 
    'persons_per_household', 'income_per_person']].describe()

,rooms_per_household,bedrooms_per_household,persons_per_household,income_per_person
count,20635.000000,20635.000000,20635.000000,20635.000000
mean,5.429009,1.100916,3.110088,52.584734
std,2.474414,0.519220,10.489428,189.899675
min,0.846154,0.121204,0.324603,0.721064
25%,4.440829,1.005525,2.422159,17.756294
50%,5.229091,1.048860,2.817391,30.124317
75%,6.052108,1.100029,3.289506,49.763999
max,141.909091,34.066667,1243.333333,11538.538462

### Ковариация и корреляция данных

Используются для количественной оценки степени влияния признаков друг на друга.

Ковариация:

$$cov(x,y)=\frac{\sum_i^n(x_i-\overline{x})(y_i-\overline{y})}{n-1}$$

In [42]:
df.cov()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,NEAR BAY,NEAR OCEAN,rooms_per_household,bedrooms_per_household,persons_per_household,income_per_person
longitude,4.014369,-3.957263,-2.650270,1.952900e+02,5.818217e+01,2.226290e+02,4.246078e+01,-0.058231,-1.065942e+04,0.319490,-0.052052,-0.298417,0.030979,-0.136822,0.012003,0.028980,-1.262675e+01
latitude,-3.957263,4.562400,0.207061,-1.688779e+02,-5.970169e+01,-2.580002e+02,-5.814559e+01,-0.323270,-3.550000e+04,-0.473578,0.348712,0.240521,-0.115655,0.562715,0.072485,0.088540,1.068620e+01
housing_median_age,-2.650270,0.207061,153.352054,-9.491973e+03,-1.613776e+03,-3.950847e+03,-1.396091e+03,-2.650003,1.565772e+05,0.302256,-1.404580,1.012889,0.089435,-4.662967,-0.390241,1.823387,4.919730e+01
total_rooms,195.290045,-168.877855,-9491.972996,4.757968e+06,8.480091e+05,2.061322e+06,7.658865e+05,820.949893,3.380005e+07,-3.200562,25.562021,-15.797022,-6.564437,722.033223,14.626432,-695.276956,-5.655572e+04
total_bedrooms,58.182168,-59.701688,-1613.775911,8.480091e+05,1.758661e+05,4.045477e+05,1.562091e+05,-6.048561,2.398701e+06,3.746469,-1.275870,-2.587317,0.116717,1.799624,8.727345,-151.134412,-1.272986e+04
population,222.629014,-258.000217,-3950.847141,2.061322e+06,4.045477e+05,1.252941e+06,3.820340e+05,9.765025,-3.119404e+06,41.255319,-10.379052,-21.595594,-9.280673,-195.385354,-42.416346,809.109356,-3.584750e+04
households,42.460777,-58.145590,-1396.090806,7.658865e+05,1.562091e+05,3.820340e+05,1.461484e+05,9.482673,2.909965e+06,8.055820,-7.076253,-1.211626,0.232059,-76.297785,-13.109330,-135.786198,-1.210572e+04
median_income,-0.058231,-0.323270,-2.650003,8.209499e+02,-6.048561e+00,9.765025e+00,9.482673e+00,3.609244,1.508320e+05,0.158909,-0.209618,0.033461,0.017248,1.536543,-0.050123,0.345606,7.719699e+01
median_house_value,-10659.415299,-35499.998424,156577.167904,3.380005e+07,2.398701e+06,-3.119404e+06,2.909965e+06,150831.963477,1.331599e+10,14672.563323,-26009.905082,5817.888665,5519.453094,43377.662298,-2734.509229,-27790.988913,2.501426e+06
<1H OCEAN,0.319490,-0.473578,0.302256,-3.200562e+00,3.746469e+00,4.125532e+01,8.055820e+00,0.158909,1.467256e+04,0.246805,-0.140528,-0.049163,-0.057114,-0.122330,-0.021821,-0.016387,-1.539184e+00
INLAND,-0.052052,0.348712,-1.404580,2.556202e+01,-1.275870e+00,-1.037905e+01,-7.076253e+00,-0.209618,-2.600991e+04,-0.140528,0.216499,-0.035144,-0.040827,0.173884,0.029612,0.083085,-7.606066e-01
NEAR BAY,-0.298417,0.240521,1.012889,-1.579702e+01,-2.587317e+00,-2.159559e+01,-1.211626e+00,0.033461,5.817889e+03,-0.049163,-0.035144,0.098590,-0.014283,-0.023041,-0.004780,-0.046630,2.010389e+00
NEAR OCEAN,0.030979,-0.115655,0.089435,-6.564437e+00,1.167174e-01,-9.280673e+00,2.320585e-01,0.017248,5.519453e+03,-0.057114,-0.040827,-0.014283,0.112224,-0.028512,-0.003011,-0.020068,2.894015e-01
rooms_per_household,-0.136822,0.562715,-4.662967,7.220332e+02,1.799624e+00,-1.953854e+02,-7.629778e+01,1.536543,4.337766e+04,-0.122330,0.173884,-0.023041,-0.028512,6.122727,0.998360,-0.032860,6.528065e+01
bedrooms_per_household,0.012003,0.072485,-0.390241,1.462643e+01,8.727345e+00,-4.241635e+01,-1.310933e+01,-0.050123,-2.734509e+03,-0.021821,0.029612,-0.004780,-0.003011,0.998360,0.269589,0.000633,1.095496e+01
persons_per_household,0.028980,0.088540,1.823387,-6.952770e+02,-1.511344e+02,8.091094e+02,-1.357862e+02,0.345606,-2.779099e+04,-0.016387,0.083085,-0.046630,-0.020068,-0.032860,0.000633,110.028109,-4.843948e+00
income_per_person,-12.626746,10.686195,49.197298,-5.655572e+04,-1.272986e+04,-3.584750e+04,-1.210572e+04,77.196991,2.501426e+06,-1.539184,-0.760607,2.010389,0.289402,65.280645,10.954959,-4.843948,3.606189e+04

Линейный коэффициент корреляции:

$$R=\frac{cov(x,y)}{\sigma_x \sigma_y}$$

In [73]:
df.corr().style.background_gradient(cmap='coolwarm').set_precision(2)

In [44]:
df.corr()['median_house_value'].sort_values()

INLAND                   -0.484423
latitude                 -0.144027
longitude                -0.046104
bedrooms_per_household   -0.045640
population               -0.024150
persons_per_household    -0.022960
total_bedrooms            0.049568
households                0.065964
housing_median_age        0.109571
income_per_person         0.114150
total_rooms               0.134283
NEAR OCEAN                0.142780
rooms_per_household       0.151917
NEAR BAY                  0.160569
<1H OCEAN                 0.255942
median_income             0.688016
median_house_value        1.000000
Name: median_house_value, dtype: float64

### Сохранение результатов

In [45]:
#df.drop('ocean_proximity', axis=1, inplace=True)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,<1H OCEAN,INLAND,NEAR BAY,NEAR OCEAN,rooms_per_household,bedrooms_per_household,persons_per_household,income_per_person
id,,,,,,,,,,,,,,,,,,
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,0,1,0,6.984127,1.023810,2.555556,258.546584
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,0,0,1,0,6.238137,0.971880,2.109842,34.574761
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,0,0,1,0,8.288136,1.073446,2.802260,146.318548
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,0,0,1,0,5.817352,1.073059,2.547945,101.130824
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,0,0,1,0,6.281853,1.081081,2.181467,68.074336

In [46]:
df.to_csv(PREPARED_DATASET_PATH, index=False, encoding='utf-8')